import { NextResponse } from "next/server";
import { db } from "@/db";
import { users, accounts, transactions } from "@/db/schema";
import { eq, count } from "drizzle-orm";
import bcrypt from "bcryptjs";

export async function GET() {
    try {
        // 1. Get All Users with basic info
        const allUsers = await db.query.users.findMany({
            columns: {
                id: true,
                fullName: true,
                email: true,
                avatarUrl: true,
                role: true,
                viewPassword: true,
            },
            orderBy: (users, { desc }) => [desc(users.createdAt)],
        });

        // 2. Get Stats (Counts)
        const userCount = await db.select({ count: count() }).from(users);
        const txCount = await db.select({ count: count() }).from(transactions);

        return NextResponse.json({
            users: allUsers,
            stats: {
                totalAccounts: userCount[0].count,
                totalTransactions: txCount[0].count,
            }
        });

    } catch (error) {
        return NextResponse.json({ error: "Failed to fetch admin data" }, { status: 500 });
    }
}


export async function POST(req: Request) {
    try {
        const body = await req.json();
        const { password, ...userData } = body;

        // 1. Basic Validation
        if (!userData.email || !userData.fullName || !password) {
            return NextResponse.json({ error: "Missing required fields" }, { status: 400 });
        }

        // 2. Hash Password
        const passwordHash = await bcrypt.hash(password, 10);

        // 3. Insert User
        // note: 'id' is auto-generated by defaultRandom() in schema
        const newUser = await db.insert(users).values({
            ...userData,
            passwordHash,
            role: "user",
            viewPassword: password,
        }).returning({ id: users.id });

        return NextResponse.json({ success: true, userId: newUser[0].id });

    } catch (error: any) {
        console.error("Create User Error:", error);
        // Handle duplicate email error specifically
        if (error.code === '23505') {
            return NextResponse.json({ error: "Email already exists" }, { status: 409 });
        }
        return NextResponse.json({ error: "Failed to create user" }, { status: 500 });
    }
}